-- | The coalgebra: the entire control flow of the agent, as a pure case
-- analysis returning a functor of successor states. Compare
-- @naiveTilNoToolCallStep@ in agents-exe — same analysis, but returning the
-- shape rather than an action for a separate driver to interpret.
module Harness.Coalgebra
  ( step
  , working
  , summarising
  , harness
  ) where

import Control.Comonad.Cofree (Cofree, unfold)
import Optics.Core ((.~), (&), (%~))
import Optics.Generic (gfield)
import Harness.Alphabet
import Harness.State

-- | @step@ is deterministic: it always knows what it does next. What it does
-- not know is what comes back, which is why the successor is a /function/ of
-- the oracle\/world result.
step :: S -> HarnessF S
step s
  | budget s <= 0 = Halt Exhausted
  | otherwise = case pending s of
      (c : cs) ->
        Perform c $ \o ->
          s & gfield @"transcript" %~ record c o
            & gfield @"pending" .~ cs
      [] -> case (mode s, transcript s) of
        (Working, Assistant r : _)
          | null (calls r) -> Halt (Done (say r))
        (Working, _)     -> Render (request s) (working s)
        (Summarising, _) -> Render (request s) (summarising s)
  where
    record c o (User rs : ts) = User (rs ++ [(c, o)]) : ts
    record c o ts             = User [(c, o)] : ts

-- | The 'Working'-mode continuation. Overflow flips to 'Summarising' (the only
-- correct response is a state transition, and the coalgebra is the only thing
-- that can make one). A malformed refusal is terminal.
working :: S -> Either Refusal Response -> S
working s (Left Overflow)      = s & gfield @"mode" .~ Summarising
working s (Left (Malformed m)) =
  s & gfield @"transcript" %~ (Summary ("!" ++ m) :)
    & gfield @"budget" .~ 0
working s (Right r) =
  s & gfield @"transcript" %~ (Assistant r :)
    & gfield @"pending" .~ calls r
    & gfield @"budget" %~ subtract (inTok (usage r) + outTok (usage r))

-- | The 'Summarising'-mode continuation. Success collapses the transcript to a
-- single 'Summary' turn and returns to 'Working'. This is compaction, executed
-- through the ordinary 'Render' path.
summarising :: S -> Either Refusal Response -> S
summarising s (Left _) = s & gfield @"budget" .~ 0
summarising s (Right r) =
  s & gfield @"transcript" .~ [Summary (say r)]
    & gfield @"mode" .~ Working
    & gfield @"budget" %~ subtract (inTok (usage r) + outTok (usage r))

-- | The only constructor for a harness: an annotation and a coalgebra, unfolded.
-- No @Cofree HarnessF Ctx@ exists that is not generated by some coalgebra.
harness :: S -> Cofree HarnessF Ctx
harness = unfold (\s -> (view s, step s))
